version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tfffoods-app:latest
    container_name: tfffoods-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.tfffoods.com
      # Add other environment variables as needed
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
