version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MONGODB_URI: ${MONGODB_URI}
        MONGO_URI: ${MONGO_URI}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        JWT_SECRET: ${JWT_SECRET}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
        CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
        CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
        NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
        NEXT_PUBLIC_CLOUDINARY_PRESET_NAME: ${NEXT_PUBLIC_CLOUDINARY_PRESET_NAME}
        NEXT_PUBLIC_CLOUDINARY_API_KEY: ${NEXT_PUBLIC_CLOUDINARY_API_KEY}
        DEFAULT_PROFILE_IMAGE: ${DEFAULT_PROFILE_IMAGE}
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
        NEXT_PUBLIC_SHOW_BRAND_BETA_ADMIN: ${NEXT_PUBLIC_SHOW_BRAND_BETA_ADMIN}
    ports:
      - "3000:3000"
    environment:
      # Brevo transactional email
      BREVO_API_KEY: ${BREVO_API_KEY}
      BREVO_SENDER_EMAIL: ${BREVO_SENDER_EMAIL}
      BREVO_SENDER_NAME: ${BREVO_SENDER_NAME}
      # Public app URL for links in emails (optional but recommended)
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
