version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      ports:
        - "3000:3000"
      args:
        - MONGODB_URI=${MONGODB_URI}
        - MONGO_URI=${MONGO_URI}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - JWT_SECRET=${JWT_SECRET}
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
        - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
        - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
        - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
        - NEXT_PUBLIC_CLOUDINARY_PRESET_NAME=${NEXT_PUBLIC_CLOUDINARY_PRESET_NAME}
        - NEXT_PUBLIC_CLOUDINARY_API_KEY=${NEXT_PUBLIC_CLOUDINARY_API_KEY}
        - DEFAULT_PROFILE_IMAGE=${DEFAULT_PROFILE_IMAGE}
        - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
        - NEXT_PUBLIC_SHOW_BRAND_BETA_ADMIN=${NEXT_PUBLIC_SHOW_BRAND_BETA_ADMIN}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
        - SENDGRID_API_KEY=dummy_key_not_used
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - MONGO_URI=${MONGO_URI}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
      - NEXT_PUBLIC_CLOUDINARY_PRESET_NAME=${NEXT_PUBLIC_CLOUDINARY_PRESET_NAME}
      - NEXT_PUBLIC_CLOUDINARY_API_KEY=${NEXT_PUBLIC_CLOUDINARY_API_KEY}
      - DEFAULT_PROFILE_IMAGE=${DEFAULT_PROFILE_IMAGE}
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
      - NEXT_PUBLIC_SHOW_BRAND_BETA_ADMIN=${NEXT_PUBLIC_SHOW_BRAND_BETA_ADMIN}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - SENDGRID_API_KEY=dummy_key_not_used
    restart: always

networks:
  app_network:
    driver: bridge
